// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBk2ELurpNmQ2nrAVd57SctXKK2HY3v8',
    appId: '1:969940299346:web:c4f14d14555853b824798b',
    messagingSenderId: '969940299346',
    projectId: 'stroke-hypertension-app',
    authDomain: 'stroke-hypertension-app.firebaseapp.com',
    storageBucket: 'stroke-hypertension-app.firebasestorage.app',
    measurementId: 'G-MC788DDZQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAch3fJkPfQBQdms4gbOqAxPP394HSDy_M',
    appId: '1:969940299346:android:fd3080683b7d299924798b',
    messagingSenderId: '969940299346',
    projectId: 'stroke-hypertension-app',
    storageBucket: 'stroke-hypertension-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsQcRzUJbV74Zp7TtvJPtdop-Dn5Dy4iA',
    appId: '1:969940299346:ios:757b1acc6b9cd6b924798b',
    messagingSenderId: '969940299346',
    projectId: 'stroke-hypertension-app',
    storageBucket: 'stroke-hypertension-app.firebasestorage.app',
    iosBundleId: 'com.example.strokeHypertensionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsQcRzUJbV74Zp7TtvJPtdop-Dn5Dy4iA',
    appId: '1:969940299346:ios:757b1acc6b9cd6b924798b',
    messagingSenderId: '969940299346',
    projectId: 'stroke-hypertension-app',
    storageBucket: 'stroke-hypertension-app.firebasestorage.app',
    iosBundleId: 'com.example.strokeHypertensionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBk2ELurpNmQ2nrAVd57SctXKK2HY3v8',
    appId: '1:969940299346:web:0923cd7db622696b24798b',
    messagingSenderId: '969940299346',
    projectId: 'stroke-hypertension-app',
    authDomain: 'stroke-hypertension-app.firebaseapp.com',
    storageBucket: 'stroke-hypertension-app.firebasestorage.app',
    measurementId: 'G-QVH43LZY53',
  );
}
